-- The owner's decision of 10.10.2026 (docs/ops.md, section 57): protocol version 9.
-- Ofir alone checks the graphics (the first 9 as the rest) and assigns the editor, each
-- on a fast ladder of its own. The protocol itself is data in app/protocol.js. The
-- database needs three things:
--   1. the clients whose first 9 graphics were already checked or sent before the
--      check passed to Ofir, and the ones whose check is under way right now;
--   2. the version;
--   3. the writers table.
-- Additive only: no table, no column, no policy; marks are added, never changed. Every
-- statement can run again safely. Tested with every migration in a real Postgres:
-- tests/sql/fast-ladder.test.mjs.

-- ── 1. The first 9 graphics of the clients that are already there ──
-- Version 9 adds one item to process 7, "אופיר אישר את הגרפיקות" (p07.ofir), and nothing
-- is sent to the client before it. Only on the move to version 9 (run again later, this
-- must not close an approval that is really waiting, so it looks at the version before
-- raising it):
--   a. the graphics were already sent to the client (p07.sent): the approval is history;
--   b. all seven checks were already ticked (Irit finished her check under version 8 and
--      has not sent yet): the approval is history too, so she sends as she was about to,
--      and Ofir is not asked to check again what was checked;
--   c. the graphics are ready and the check is not finished (nothing ticked, or some of
--      the seven): what was ticked stays, the rest is Ofir's, and one mark (p07.moved)
--      says when it passed to him. His ten minutes are counted from that moment, never
--      from the hour Ilai handed the graphics over under the old way of working.
--      Not for a client in landing and not for imported history: nothing of them is rung.
-- Imported history (note 'ייבוא'): done, never counted as work or late.
do $$
begin
  if private.protocol_version_current() < 9 then
    insert into public.protocol_checks (client_id, item_key, state, note)
    select a.client_id, 'p07.ofir', 'done', 'ייבוא'
    from public.protocol_checks a
    where a.item_key = 'p07.sent' and a.state in ('done', 'na')
    on conflict (client_id, item_key) do nothing;

    insert into public.protocol_checks (client_id, item_key, state, note)
    select a.client_id, 'p07.ofir', 'done', 'ייבוא'
    from public.protocol_checks a
    where a.item_key in ('p07.r.spelling', 'p07.r.phone', 'p07.r.address', 'p07.r.logo', 'p07.r.details', 'p07.r.wording', 'p07.r.design')
      and a.state in ('done', 'na')
    group by a.client_id
    having count(*) = 7
    on conflict (client_id, item_key) do nothing;

    insert into public.protocol_checks (client_id, item_key, state, note)
    select m.client_id, 'p07.moved', 'done', 'גרסה 9: הבדיקה עברה לאופיר'
    from public.protocol_checks m
    join public.clients c on c.id = m.client_id
    where m.item_key = 'p07.made' and m.state = 'done' and m.note is distinct from 'ייבוא'
      and c.landing = false and c.status in ('active', 'ending')
      and not exists (select 1 from public.protocol_checks o
                      where o.client_id = m.client_id and o.item_key in ('p07.ofir', 'p07.sent'))
    on conflict (client_id, item_key) do nothing;
  end if;
end $$;

-- ── 2. Protocol version 9 ────────────────────
create or replace function private.protocol_version_current() returns integer
language sql immutable set search_path = '' as $$ select 9 $$;
revoke all on function private.protocol_version_current() from public, anon, authenticated;
alter table public.clients alter column protocol_version set default 9;

-- ── 3. Who writes which protocol item (v9) ───
-- The office (Irit, Lior, Ofir) writes every key, so the seven checks moving from Irit
-- to Ofir and Lior leaving the assignment change no row by themselves. What changes:
--   p07.@wait, p07.@part   Ofir joins Ilai and Irit (he now has items in process 7);
--   p07.@qafixed           new: Ilai marks "תוקן" on what Ofir returned of the first 9
--                          graphics (p07.fixed.N), as he does for the rest (p23.@qafixed).
-- protocol-writers:begin (generated by scripts/protocol-writers.mjs from app/protocol.js; do not edit by hand)
insert into private.protocol_writers (key, proc, round, persons) values
  ('@office', null, false, array['irit', 'lior', 'ofir']::text[]),
  ('@editors', null, false, array['anna', 'nadia', 'nirel', 'yariv']::text[]),
  ('p05.newlogo', 'p05', false, array['ilai']::text[]),
  ('p05.@wait', 'p05', false, array['ilai', 'irit', 'lior', 'ofir']::text[]),
  ('p05.@part', 'p05', false, array['ilai', 'irit', 'lior', 'ofir']::text[]),
  ('p06.verified', 'p06', false, array['ilai']::text[]),
  ('p06.newpages', 'p06', false, array['ilai']::text[]),
  ('p06.name', 'p06', false, array['ilai']::text[]),
  ('p06.bio', 'p06', false, array['ilai']::text[]),
  ('p06.details', 'p06', false, array['ilai']::text[]),
  ('p06.phone', 'p06', false, array['ilai']::text[]),
  ('p06.address', 'p06', false, array['ilai']::text[]),
  ('p06.look', 'p06', false, array['ilai']::text[]),
  ('p06.metricool', 'p06', false, array['ilai']::text[]),
  ('p06.@part', 'p06', false, array['ilai', 'lior']::text[]),
  ('p07.made', 'p07', false, array['ilai']::text[]),
  ('p07.@wait', 'p07', false, array['ilai', 'irit', 'ofir']::text[]),
  ('p07.@part', 'p07', false, array['ilai', 'irit', 'ofir']::text[]),
  ('p07b.posted', 'p07b', false, array['ilai']::text[]),
  ('p07b.@part', 'p07b', false, array['ilai']::text[]),
  ('p09.file', 'p09', false, array['ilai']::text[]),
  ('p09.c.name', 'p09', false, array['ilai']::text[]),
  ('p09.c.months', 'p09', false, array['ilai']::text[]),
  ('p09.c.num', 'p09', false, array['ilai']::text[]),
  ('p09.c.link', 'p09', false, array['ilai']::text[]),
  ('p09.c.day', 'p09', false, array['ilai']::text[]),
  ('p09.c.date', 'p09', false, array['ilai']::text[]),
  ('p09.c.time', 'p09', false, array['ilai']::text[]),
  ('p09.@part', 'p09', false, array['ilai']::text[]),
  ('p17b.arrived', 'p17b', true, array['eli']::text[]),
  ('p17b.drive', 'p17b', true, array['eli']::text[]),
  ('p17b.gear', 'p17b', true, array['eli']::text[]),
  ('p17b.zones', 'p17b', true, array['eli']::text[]),
  ('p17b.broll', 'p17b', true, array['eli']::text[]),
  ('p17b.variety', 'p17b', true, array['eli']::text[]),
  ('p17b.@part', 'p17b', true, array['eli']::text[]),
  ('p18b.order', 'p18b', true, array['eli']::text[]),
  ('p18b.quality', 'p18b', true, array['eli']::text[]),
  ('p18b.numbered', 'p18b', true, array['eli']::text[]),
  ('p18b.@part', 'p18b', true, array['eli']::text[]),
  ('p19b.folders', 'p19b', true, array['eli']::text[]),
  ('p19b.complete', 'p19b', true, array['eli']::text[]),
  ('p19b.opens', 'p19b', true, array['eli']::text[]),
  ('p19b.cards', 'p19b', true, array['eli']::text[]),
  ('p19b.handed', 'p19b', true, array['eli']::text[]),
  ('p19b.notes', 'p19b', true, array['eli']::text[]),
  ('p19b.@part', 'p19b', true, array['eli']::text[]),
  ('p22.received', 'p22', true, array['@editor']::text[]),
  ('p22.check.footage', 'p22', true, array['@editor']::text[]),
  ('p22.check.scripts', 'p22', true, array['@editor']::text[]),
  ('p22.check.logo', 'p22', true, array['@editor']::text[]),
  ('p22.check.phone', 'p22', true, array['@editor']::text[]),
  ('p22.edited', 'p22', true, array['@editor']::text[]),
  ('p22.self.spelling', 'p22', true, array['@editor']::text[]),
  ('p22.self.broll', 'p22', true, array['@editor']::text[]),
  ('p22.self.closing', 'p22', true, array['@editor']::text[]),
  ('p22.self.complete', 'p22', true, array['@editor']::text[]),
  ('p22.@wait', 'p22', true, array['@editor']::text[]),
  ('p22.@pause', 'p22', true, array['@editor', '@editor-free']::text[]),
  ('p22.@part', 'p22', true, array['@editor']::text[]),
  ('p23.made', 'p23', false, array['ilai']::text[]),
  ('p23.@wait', 'p23', false, array['ilai', 'irit', 'ofir']::text[]),
  ('p23.@part', 'p23', false, array['ilai', 'irit', 'ofir']::text[]),
  ('p23b.posted', 'p23b', false, array['ilai']::text[]),
  ('p23b.@part', 'p23b', false, array['ilai']::text[]),
  ('p24.drive', 'p24', true, array['@editor']::text[]),
  ('p24.d' || 'ropbox', 'p24', true, array['@editor']::text[]),
  ('p24.notify', 'p24', true, array['@editor']::text[]),
  ('p24.@wait', 'p24', true, array['@editor', 'ofir']::text[]),
  ('p24.@part', 'p24', true, array['@editor', 'ofir']::text[]),
  ('p27.fixes', 'p27', true, array['@editor']::text[]),
  ('p27.final', 'p27', true, array['@editor']::text[]),
  ('p27.toilai', 'p27', true, array['ilai']::text[]),
  ('p27.@wait', 'p27', true, array['@editor', 'ilai', 'irit']::text[]),
  ('p27.@pause', 'p27', true, array['@editor', '@editor-free']::text[]),
  ('p27.@part', 'p27', true, array['@editor', 'ilai', 'irit']::text[]),
  ('p28.scheduled', 'p28', true, array['ilai']::text[]),
  ('p28.@part', 'p28', true, array['ilai']::text[]),
  ('p29.filled', 'p29', true, array['ilai']::text[]),
  ('p29.@claim', 'p29', true, array['ilai', 'irit']::text[]),
  ('p29.@part', 'p29', true, array['ilai', 'irit']::text[]),
  ('p17b.brollq', 'p17b', true, array['eli']::text[]),
  ('p22.missing', 'p22', true, array['@editor']::text[]),
  ('p27.fixed', 'p27', true, array['@editor']::text[]),
  ('p25.@qafixed', 'p25', true, array['@editor']::text[]),
  ('p23.@qafixed', 'p23', false, array['ilai']::text[]),
  ('p07.@qafixed', 'p07', false, array['ilai']::text[])
on conflict (key) do update set proc = excluded.proc, round = excluded.round, persons = excluded.persons;
update private.protocol_writers set persons = '{}'::text[] where key <> all (array['@office', '@editors', 'p05.newlogo', 'p05.@wait', 'p05.@part', 'p06.verified', 'p06.newpages', 'p06.name', 'p06.bio', 'p06.details', 'p06.phone', 'p06.address', 'p06.look', 'p06.metricool', 'p06.@part', 'p07.made', 'p07.@wait', 'p07.@part', 'p07b.posted', 'p07b.@part', 'p09.file', 'p09.c.name', 'p09.c.months', 'p09.c.num', 'p09.c.link', 'p09.c.day', 'p09.c.date', 'p09.c.time', 'p09.@part', 'p17b.arrived', 'p17b.drive', 'p17b.gear', 'p17b.zones', 'p17b.broll', 'p17b.variety', 'p17b.@part', 'p18b.order', 'p18b.quality', 'p18b.numbered', 'p18b.@part', 'p19b.folders', 'p19b.complete', 'p19b.opens', 'p19b.cards', 'p19b.handed', 'p19b.notes', 'p19b.@part', 'p22.received', 'p22.check.footage', 'p22.check.scripts', 'p22.check.logo', 'p22.check.phone', 'p22.edited', 'p22.self.spelling', 'p22.self.broll', 'p22.self.closing', 'p22.self.complete', 'p22.@wait', 'p22.@pause', 'p22.@part', 'p23.made', 'p23.@wait', 'p23.@part', 'p23b.posted', 'p23b.@part', 'p24.drive', 'p24.d' || 'ropbox', 'p24.notify', 'p24.@wait', 'p24.@part', 'p27.fixes', 'p27.final', 'p27.toilai', 'p27.@wait', 'p27.@pause', 'p27.@part', 'p28.scheduled', 'p28.@part', 'p29.filled', 'p29.@claim', 'p29.@part', 'p17b.brollq', 'p22.missing', 'p27.fixed', 'p25.@qafixed', 'p23.@qafixed', 'p07.@qafixed']::text[]);
-- protocol-writers:end
