-- Hardening after the review of stages 4–6 (docs/ops.md, section 18):
--   1. The office's columns of a client (the client's own phone, the office's notes,
--      why an agreement was cancelled) are the office's alone. Row level security
--      chooses rows, not columns: until now an editor, Nirel or Eli could read them
--      from any client they see by asking for them. Now `authenticated` may select
--      every other column of public.clients, and the office reads these three through
--      public.clients_private(). Nothing moves: the data stays in its place.
--      The signed agreements (public.quotes) carry the same phone and the prices, so
--      they too are read by the office only.
--   2. A protocol item is written or cleared only by whoever the app lets write it
--      (private.protocol_writers, generated from app/protocol.js by
--      scripts/protocol-writers.mjs): the owner, Irit, Lior and Ofir everything; Ilai,
--      Eli and the editors only their own items and marks. Imported history ('ייבוא')
--      only by the office. The monthly cycle: Ilai marks only his own items.
--   3. The status page: an approval or a fix request is applied once even when sent
--      twice at once (the client's row is locked), and approving the scripts while the
--      Zoom (13) is still open marks the Zoom 'na' ("אושר בדף המצב"), so process 13
--      closes and nothing reminds about a Zoom that is no longer needed (decision in
--      docs/ops.md, section 17). A revoked status link's token leaves Vault.
-- Publish the site BEFORE applying this: the pages before it ask public.clients for
-- the phone directly, which is refused from here on (app/protocol-data.js now reads it
-- through clients_private(), and falls back to the table while the function is missing).
-- Every statement can run again safely. Tested in tests/sql/hardening.test.mjs.

-- ── 1. The office's columns of a client ──────
-- Whatever a signed-in user may select from public.clients: every column but phone,
-- notes and closed_reason. A new column on clients needs its own grant here, in the
-- migration that adds it (tests/sql/hardening.test.mjs lists them).
revoke all on public.clients from anon;
revoke select on public.clients from authenticated;
grant select (id, name, business, package_name, shoot_type, characterizer, has_logo, editor_name,
  deal_at, char_at, shoot_at, contract_end, status, quote_id, protocol_version, created_at,
  created_by_email, updated_at, address, links, deliverables, rounds, verified_at, verified_by, editor)
  on public.clients to authenticated;

-- The office's three columns, for the office only (anyone else gets no rows). All
-- clients when p_ids is null.
create or replace function public.clients_private(p_ids uuid[] default null)
returns table (id uuid, phone text, notes text, closed_reason text)
language sql stable security definer set search_path = '' as $$
  select c.id, c.phone, c.notes, c.closed_reason
  from public.clients c
  where (select public.is_office()) and (p_ids is null or c.id = any (p_ids));
$$;
revoke execute on function public.clients_private(uuid[]) from public, anon;
grant execute on function public.clients_private(uuid[]) to authenticated;

-- The signed agreements: the office (the payouts app and the quote builder are theirs).
drop policy if exists "staff read quotes" on public.quotes;
drop policy if exists "office reads quotes" on public.quotes;
create policy "office reads quotes" on public.quotes
  for select to authenticated using ((select public.is_office()));

-- The same tables, never for anon (their policies are for signed-in users anyway).
revoke all on public.protocol_checks, public.protocol_log, public.client_tasks from anon;

-- ── 2. Who writes which protocol item ────────
create table if not exists private.protocol_writers (
  key text primary key,          -- an item or mark without the round prefix, or a rule ('p22.@wait')
  proc text,                     -- its process
  round boolean not null default false, -- the process repeats in a shoot round ('r2.' keys)
  persons text[] not null        -- people; '@editor' the editor of that shoot; '@editor-free' any editor while it has none
);
alter table private.protocol_writers enable row level security;
revoke all on private.protocol_writers from public, anon, authenticated;

-- protocol-writers:begin (generated by scripts/protocol-writers.mjs from app/protocol.js; do not edit by hand)
delete from private.protocol_writers;
insert into private.protocol_writers (key, proc, round, persons) values
  ('@office', null, false, array['irit', 'lior', 'ofir']::text[]),
  ('@editors', null, false, array['anna', 'nadia', 'nirel', 'yariv']::text[]),
  ('p05.newlogo', 'p05', false, array['ilai']::text[]),
  ('p05.@wait', 'p05', false, array['ilai', 'irit', 'lior', 'ofir']::text[]),
  ('p05.@part', 'p05', false, array['ilai', 'irit', 'lior', 'ofir']::text[]),
  ('p06.verified', 'p06', false, array['ilai']::text[]),
  ('p06.newpages', 'p06', false, array['ilai']::text[]),
  ('p06.name', 'p06', false, array['ilai']::text[]),
  ('p06.bio', 'p06', false, array['ilai']::text[]),
  ('p06.details', 'p06', false, array['ilai']::text[]),
  ('p06.phone', 'p06', false, array['ilai']::text[]),
  ('p06.address', 'p06', false, array['ilai']::text[]),
  ('p06.look', 'p06', false, array['ilai']::text[]),
  ('p06.metricool', 'p06', false, array['ilai']::text[]),
  ('p06.@part', 'p06', false, array['ilai', 'lior']::text[]),
  ('p07.made', 'p07', false, array['ilai']::text[]),
  ('p07.@wait', 'p07', false, array['ilai', 'irit', 'lior']::text[]),
  ('p07.@part', 'p07', false, array['ilai', 'irit', 'lior']::text[]),
  ('p09.file', 'p09', false, array['ilai']::text[]),
  ('p09.c.name', 'p09', false, array['ilai']::text[]),
  ('p09.c.months', 'p09', false, array['ilai']::text[]),
  ('p09.c.num', 'p09', false, array['ilai']::text[]),
  ('p09.c.link', 'p09', false, array['ilai']::text[]),
  ('p09.c.day', 'p09', false, array['ilai']::text[]),
  ('p09.c.date', 'p09', false, array['ilai']::text[]),
  ('p09.c.time', 'p09', false, array['ilai']::text[]),
  ('p09.@part', 'p09', false, array['ilai']::text[]),
  ('p17b.arrived', 'p17b', true, array['eli']::text[]),
  ('p17b.drive', 'p17b', true, array['eli']::text[]),
  ('p17b.gear', 'p17b', true, array['eli']::text[]),
  ('p17b.zones', 'p17b', true, array['eli']::text[]),
  ('p17b.broll', 'p17b', true, array['eli']::text[]),
  ('p17b.variety', 'p17b', true, array['eli']::text[]),
  ('p17b.@part', 'p17b', true, array['eli']::text[]),
  ('p18b.order', 'p18b', true, array['eli']::text[]),
  ('p18b.quality', 'p18b', true, array['eli']::text[]),
  ('p18b.numbered', 'p18b', true, array['eli']::text[]),
  ('p18b.@part', 'p18b', true, array['eli']::text[]),
  ('p19b.folders', 'p19b', true, array['eli']::text[]),
  ('p19b.complete', 'p19b', true, array['eli']::text[]),
  ('p19b.opens', 'p19b', true, array['eli']::text[]),
  ('p19b.cards', 'p19b', true, array['eli']::text[]),
  ('p19b.handed', 'p19b', true, array['eli']::text[]),
  ('p19b.notes', 'p19b', true, array['eli']::text[]),
  ('p19b.@part', 'p19b', true, array['eli']::text[]),
  ('p22.received', 'p22', true, array['@editor']::text[]),
  ('p22.check.footage', 'p22', true, array['@editor']::text[]),
  ('p22.check.scripts', 'p22', true, array['@editor']::text[]),
  ('p22.check.logo', 'p22', true, array['@editor']::text[]),
  ('p22.check.phone', 'p22', true, array['@editor']::text[]),
  ('p22.edited', 'p22', true, array['@editor']::text[]),
  ('p22.self.spelling', 'p22', true, array['@editor']::text[]),
  ('p22.self.broll', 'p22', true, array['@editor']::text[]),
  ('p22.self.closing', 'p22', true, array['@editor']::text[]),
  ('p22.self.complete', 'p22', true, array['@editor']::text[]),
  ('p22.@wait', 'p22', true, array['@editor']::text[]),
  ('p22.@pause', 'p22', true, array['@editor', '@editor-free']::text[]),
  ('p22.@part', 'p22', true, array['@editor']::text[]),
  ('p23.made', 'p23', false, array['ilai']::text[]),
  ('p23.@wait', 'p23', false, array['ilai', 'irit', 'ofir']::text[]),
  ('p23.@part', 'p23', false, array['ilai', 'irit', 'ofir']::text[]),
  ('p24.drive', 'p24', true, array['@editor']::text[]),
  ('p24.dropbox', 'p24', true, array['@editor']::text[]),
  ('p24.notify', 'p24', true, array['@editor']::text[]),
  ('p24.@wait', 'p24', true, array['@editor', 'ofir']::text[]),
  ('p24.@part', 'p24', true, array['@editor', 'ofir']::text[]),
  ('p27.fixes', 'p27', true, array['@editor']::text[]),
  ('p27.final', 'p27', true, array['@editor']::text[]),
  ('p27.toilai', 'p27', true, array['ilai']::text[]),
  ('p27.@wait', 'p27', true, array['@editor', 'ilai', 'irit']::text[]),
  ('p27.@pause', 'p27', true, array['@editor', '@editor-free']::text[]),
  ('p27.@part', 'p27', true, array['@editor', 'ilai', 'irit']::text[]),
  ('p28.scheduled', 'p28', true, array['ilai']::text[]),
  ('p28.@part', 'p28', true, array['ilai']::text[]),
  ('p29.filled', 'p29', true, array['ilai']::text[]),
  ('p29.@claim', 'p29', true, array['ilai', 'irit']::text[]),
  ('p29.@part', 'p29', true, array['ilai', 'irit']::text[]),
  ('p17b.brollq', 'p17b', true, array['eli']::text[]),
  ('p22.missing', 'p22', true, array['@editor']::text[]),
  ('p27.fixed', 'p27', true, array['@editor']::text[]),
  ('p25.@qafixed', 'p25', true, array['@editor']::text[]),
  ('p23.@qafixed', 'p23', false, array['ilai']::text[]);
-- protocol-writers:end

-- Whether the signed-in person may write (mark, change or clear) this key on this
-- client: the same decision as mayWrite() in scripts/protocol-writers.mjs (the tests
-- compare the two). p_note is the note written; null when clearing, and for the
-- row an update replaces (imported history may be re-marked by its owner).
create or replace function private.protocol_write_ok(p_client uuid, p_key text, p_note text)
returns boolean
language plpgsql stable security definer set search_path = '' as $$
declare
  me text;
  m text[];
  w private.protocol_writers;
  v_rule text;
  v_editor text;
begin
  if not public.is_staff() then return false; end if;
  me := public.my_person();
  -- The owner (a staff login without a person), Irit, Lior and Ofir: everything.
  if me is null then return public.is_office(); end if;
  if me = any (coalesce((select w0.persons from private.protocol_writers w0 where w0.key = '@office'), '{}')) then return true; end if;
  -- Imported history is written when the office opens a client.
  if p_note = 'ייבוא' then return false; end if;
  m := regexp_match(coalesce(p_key, ''), '^(?:r([0-9]+)\.)?((p[0-9]+[ab]?)\.(.+))$');
  if m is null then return false; end if;
  -- "לדחות…" on a reminder: on any client one sees, as before.
  if m[4] = 'snooze' then return true; end if;
  select * into w from private.protocol_writers x where x.key = m[2];
  if not found then
    v_rule := case
      when m[4] = 'claim' then m[3] || '.@claim'
      when m[4] in ('wait', 'waited') then m[3] || '.@wait'
      when m[4] = 'pause' then m[3] || '.@pause'
      when m[4] ~ '^handoff\.[a-z0-9]+$' then m[3] || '.@part'
      when m[4] ~ '^fixed\.[0-9]+(\.[0-9]+)?$' then m[3] || '.@qafixed' end;
    select * into w from private.protocol_writers x where x.key = v_rule;
  end if;
  if w.key is null or (m[1] is not null and not w.round) then return false; end if;
  if me = any (w.persons) then return true; end if;
  if not (w.persons && array['@editor', '@editor-free']) then return false; end if;
  -- The editor of that shoot: the client's, or the round's (no fallback, as in the app).
  select case when m[1] is null then c.editor
              else (select r ->> 'editor' from jsonb_array_elements(c.rounds) r where r ->> 'n' = m[1] limit 1) end
    into v_editor
  from public.clients c where c.id = p_client;
  return ('@editor' = any (w.persons) and v_editor is not null and v_editor = me)
    or ('@editor-free' = any (w.persons) and v_editor is null
        and me = any (coalesce((select w1.persons from private.protocol_writers w1 where w1.key = '@editors'), '{}')));
end $$;
revoke execute on function private.protocol_write_ok(uuid, text, text) from public, anon;
-- The policies below call it as the signed-in user.
grant execute on function private.protocol_write_ok(uuid, text, text) to authenticated;

-- Read on the clients one sees (as before); write only what one may write.
drop policy if exists "checks of own clients" on public.protocol_checks;
drop policy if exists "read checks of own clients" on public.protocol_checks;
drop policy if exists "mark own items" on public.protocol_checks;
drop policy if exists "change own items" on public.protocol_checks;
drop policy if exists "clear own items" on public.protocol_checks;
create policy "read checks of own clients" on public.protocol_checks
  for select to authenticated
  using ((select public.is_office()) or client_id in (select private.my_clients()));
create policy "mark own items" on public.protocol_checks
  for insert to authenticated
  with check (((select public.is_office()) or client_id in (select private.my_clients()))
    and private.protocol_write_ok(client_id, item_key, note));
create policy "change own items" on public.protocol_checks
  for update to authenticated
  using (((select public.is_office()) or client_id in (select private.my_clients()))
    and private.protocol_write_ok(client_id, item_key, null))
  with check (((select public.is_office()) or client_id in (select private.my_clients()))
    and private.protocol_write_ok(client_id, item_key, note));
create policy "clear own items" on public.protocol_checks
  for delete to authenticated
  using (((select public.is_office()) or client_id in (select private.my_clients()))
    and private.protocol_write_ok(client_id, item_key, null));

-- The monthly cycle (a draft): the owner, Irit, Lior and Ofir mark any item (also
-- for someone else, decision 23); Ilai only his own ('plan', 'posted' in
-- app/year-logic.js; tests/sql/hardening.test.mjs compares).
create or replace function private.month_write_ok(p_item text) returns boolean
language sql stable security definer set search_path = '' as $$
  select public.is_office() and (public.my_person() is distinct from 'ilai'
    or split_part(coalesce(p_item, ''), '.', 1) in ('plan', 'posted'));
$$;
revoke execute on function private.month_write_ok(text) from public, anon;
grant execute on function private.month_write_ok(text) to authenticated;
drop policy if exists "office manages month marks" on public.client_month_marks;
drop policy if exists "office reads month marks" on public.client_month_marks;
drop policy if exists "office marks month items" on public.client_month_marks;
drop policy if exists "office changes month items" on public.client_month_marks;
drop policy if exists "office clears month items" on public.client_month_marks;
create policy "office reads month marks" on public.client_month_marks
  for select to authenticated using ((select public.is_office()));
create policy "office marks month items" on public.client_month_marks
  for insert to authenticated with check (private.month_write_ok(item));
create policy "office changes month items" on public.client_month_marks
  for update to authenticated using (private.month_write_ok(item)) with check (private.month_write_ok(item));
create policy "office clears month items" on public.client_month_marks
  for delete to authenticated using (private.month_write_ok(item));

-- ── 3. The status page ───────────────────────
-- A revoked link's token leaves Vault (a new link revokes the one before it).
create or replace function public.client_status_links_forget() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.revoked_at is not null and old.secret_id is not null then
    delete from vault.secrets where id = old.secret_id;
    new.secret_id := null;
  end if;
  return new;
end $$;
revoke execute on function public.client_status_links_forget() from public, anon, authenticated;
drop trigger if exists client_status_links_forget on public.client_status_links;
create trigger client_status_links_forget before update on public.client_status_links
for each row execute function public.client_status_links_forget();
-- The links revoked before this migration.
delete from vault.secrets v using public.client_status_links l
  where l.revoked_at is not null and l.secret_id = v.id;
update public.client_status_links set secret_id = null where revoked_at is not null and secret_id is not null;

-- "מאשר/ת": as in 20260930170000_client_status.sql, plus the lock (a second press
-- sent at the same moment finds the item approved) and the Zoom (13).
create or replace function public.approve_item(p_token text, p_key text, p_name text, p_wording text, p_note text default null)
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  l record;
  c public.clients;
  it jsonb;
  v_name text := private.clean_name(p_name);
  v_note text := nullif(btrim(coalesce(p_note, '')), '');
  v_wording text;
  v_now timestamptz := now();
begin
  select * into l from private.status_actor(p_token, p_name);
  if char_length(coalesce(v_note, '')) > 2000 then raise exception 'note too long' using errcode = '22023'; end if;
  select * into c from public.clients where id = l.client_id for update;
  select x.value into it from jsonb_array_elements(private.status_items(c.id)) as x where x.value ->> 'key' = p_key;
  if it is null or it ->> 'state' <> 'waiting' then
    raise exception 'not awaiting approval' using errcode = '22023';
  end if;
  v_wording := private.status_wording('approve', v_name, coalesce(nullif(btrim(c.business), ''), c.name), it ->> 'item', (it ->> 'shootRound')::int, (it ->> 'round')::int);
  if p_wording is distinct from v_wording then
    raise exception 'wording changed' using errcode = '22023';
  end if;
  insert into public.client_approvals (client_id, link_id, item, item_key, shoot_round, decision, round, signer_name, note, wording,
    file_ref, version, ip, user_agent, at, evidence_hash)
  values (c.id, l.link_id, it ->> 'item', p_key, (it ->> 'shootRound')::int, 'approve', (it ->> 'round')::int, v_name, v_note, v_wording,
    it ->> 'link', it ->> 'sentAt', private.request_ip(), private.request_ua(), v_now,
    encode(extensions.digest(convert_to(concat_ws('|', c.id, p_key, 'approve', it ->> 'round', v_name, v_wording, v_note, it ->> 'link', it ->> 'sentAt',
      to_char(v_now at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')), 'UTF8'), 'sha256'), 'hex'));
  insert into public.protocol_checks (client_id, item_key, state, note)
  values (c.id, p_key, 'done', left('אושר בדף המצב על ידי ' || v_name, 2000))
  on conflict (client_id, item_key) do update set state = 'done', note = excluded.note;
  -- The scripts approved here while the Zoom was still open: the Zoom is not needed
  -- any more ('na', so process 13 closes). A Zoom already marked stays as it is, and
  -- Lior can still mark it done if it took place.
  if p_key ~ '^(r[0-9]+\.)?p13\.approved$' then
    insert into public.protocol_checks (client_id, item_key, state, note)
    values (c.id, regexp_replace(p_key, 'approved$', 'zoom'), 'na', 'אושר בדף המצב')
    on conflict (client_id, item_key) do nothing;
  end if;
  return public.get_status(p_token);
end $$;

-- "מבקש/ת תיקון": as in 20260930170000_client_status.sql, plus the lock, so a request
-- sent twice at once opens one task (and rings once).
create or replace function public.request_fix(p_token text, p_key text, p_name text, p_wording text, p_note text)
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  l record;
  c public.clients;
  it jsonb;
  v_name text := private.clean_name(p_name);
  v_note text := btrim(coalesce(p_note, ''));
  v_wording text;
  v_now timestamptz := now();
  v_round integer;
  v_extra boolean;
  v_item text;
  v_pre text;
  v_owner text;
  v_marked boolean := false;
  v_local timestamp := now() at time zone 'Asia/Jerusalem';
  v_due date;
  v_task uuid := gen_random_uuid();
  v_id uuid := gen_random_uuid();
begin
  select * into l from private.status_actor(p_token, p_name);
  if char_length(v_note) < 2 then raise exception 'note required' using errcode = '22023'; end if;
  if char_length(v_note) > 4000 then raise exception 'note too long' using errcode = '22023'; end if;
  select * into c from public.clients where id = l.client_id for update;
  select x.value into it from jsonb_array_elements(private.status_items(c.id)) as x where x.value ->> 'key' = p_key;
  if it is null or it ->> 'state' <> 'waiting' then
    raise exception 'not awaiting approval' using errcode = '22023';
  end if;
  v_item := it ->> 'item';
  v_round := (it ->> 'round')::int;
  v_extra := v_round > (it ->> 'included')::int;
  v_pre := coalesce(substring(p_key from '^(r[0-9]+\.)'), '');
  v_wording := private.status_wording('fix', v_name, coalesce(nullif(btrim(c.business), ''), c.name), v_item, (it ->> 'shootRound')::int, v_round);
  if p_wording is distinct from v_wording then
    raise exception 'wording changed' using errcode = '22023';
  end if;
  v_owner := case
    when v_extra then 'lior'
    when v_item = 'scripts' then 'lior'
    when v_item in ('graphics9', 'graphics') then 'ilai'
    else coalesce(nullif(it ->> 'editor', ''), 'ofir') end;
  if v_owner not in ('irit', 'lior', 'ofir', 'ilai', 'nirel', 'nadia', 'yariv', 'anna', 'eli') then v_owner := 'ofir'; end if;
  v_due := case
    when v_extra or v_item = 'scripts' or extract(dow from v_local) in (5, 6) or v_local::time >= time '13:00'
      then private.next_workday(v_local::date)
    else v_local::date end;
  if v_item = 'videos' and not v_extra and not exists (
      select 1 from public.protocol_checks s where s.client_id = c.id and s.item_key = v_pre || 'p27.notes' and s.state = 'done') then
    insert into public.protocol_checks (client_id, item_key, state, note)
    values (c.id, v_pre || 'p27.notes', 'done', jsonb_build_object('text', v_note, 'via', 'status')::text)
    on conflict (client_id, item_key) do update set state = 'done', note = excluded.note;
    v_marked := true;
  end if;
  insert into public.client_tasks (id, client_id, title, owner, due_on, source, brief)
  values (v_task, c.id,
    left(case when v_extra then 'הלקוח ביקש סבב תיקונים נוסף: ' || private.status_item_text(v_item, (it ->> 'shootRound')::int, 'label') || ' (להחליט ולחזור ללקוח)'
              else 'תיקון לבקשת הלקוח: ' || private.status_item_text(v_item, (it ->> 'shootRound')::int, 'label') || ' · סבב ' || v_round end, 500),
    v_owner, v_due, 'client_fix',
    jsonb_build_object('problem', left(v_note, 4000), 'from', 'status', 'item', v_item, 'item_key', p_key, 'round', v_round,
      'extra', v_extra, 'notes_marked', v_marked, 'approval', v_id, 'by', v_name));
  insert into public.client_approvals (id, client_id, link_id, item, item_key, shoot_round, decision, round, signer_name, note, wording,
    file_ref, version, ip, user_agent, at, evidence_hash, task_id)
  values (v_id, c.id, l.link_id, v_item, p_key, (it ->> 'shootRound')::int, 'fix', v_round, v_name, v_note, v_wording,
    it ->> 'link', it ->> 'sentAt', private.request_ip(), private.request_ua(), v_now,
    encode(extensions.digest(convert_to(concat_ws('|', c.id, p_key, 'fix', v_round, v_name, v_wording, v_note, it ->> 'link', it ->> 'sentAt',
      to_char(v_now at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')), 'UTF8'), 'sha256'), 'hex'),
    v_task);
  return public.get_status(p_token);
end $$;

revoke all on function public.approve_item(text, text, text, text, text) from public;
revoke all on function public.request_fix(text, text, text, text, text) from public;
grant execute on function public.approve_item(text, text, text, text, text) to anon, authenticated;
grant execute on function public.request_fix(text, text, text, text, text) to anon, authenticated;
