-- The owner's decisions of 8.10.2026 after the full-flow simulation of one client
-- (docs/design/full-flow/report.md; docs/ops.md, section 49): protocol version 8.
-- The protocol itself is data in app/protocol.js. The database needs four things:
--   1. the history of clients that were already past the two new steps when they came
--      (the links to the client: 5ב, 7א; "no other network": p05.allnets);
--   2. the version;
--   3. the client's own logins form closing "send the client the link" by itself;
--   4. the writers table.
-- Additive only: no table, no column, no policy; marks are added, never changed. Every
-- statement can run again safely. Tested with every migration in a real Postgres:
-- tests/sql/flow-fixes.test.mjs.

-- ── 1. Clients that were past the new steps before they existed ──
-- Where the access was already received (p05.access done or "לא רלוונטי"), the link to
-- the logins form has nothing left to ask for and nobody is asked again which networks
-- are missing; where the first graphics were already sent to the client (p07.sent),
-- the client already has the status page. Imported history (note 'ייבוא'): done, never
-- counted as work or late. Only on the move to version 8: run again later, this must not
-- close a step that is really waiting, so it looks at the version before raising it.
do $$
begin
  if private.protocol_version_current() < 8 then
    insert into public.protocol_checks (client_id, item_key, state, note)
    select a.client_id, k.key, 'done', 'ייבוא'
    from public.protocol_checks a
    cross join (values ('p05b.sent'), ('p05.allnets')) as k (key)
    where a.item_key = 'p05.access' and a.state in ('done', 'na')
    on conflict (client_id, item_key) do nothing;

    insert into public.protocol_checks (client_id, item_key, state, note)
    select a.client_id, 'p07a.sent', 'done', 'ייבוא'
    from public.protocol_checks a
    where a.item_key = 'p07.sent' and a.state in ('done', 'na')
    on conflict (client_id, item_key) do nothing;
  end if;
end $$;

-- ── 2. Protocol version 8 ────────────────────
create or replace function private.protocol_version_current() returns integer
language sql immutable set search_path = '' as $$ select 8 $$;
revoke all on function private.protocol_version_current() from public, anon, authenticated;
alter table public.clients alter column protocol_version set default 8;

-- ── 3. The client filled the logins form ─────
-- public.access_form_submit() stamps submitted_at on the link. That moment closes
-- Irit's "send the client the link" (5ב) and answers "are there other networks": the
-- client listed its own. A mark already done keeps its time and its words.
create or replace function public.client_access_links_filled() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.submitted_at is not null and old.submitted_at is null then
    insert into public.protocol_checks (client_id, item_key, state, note) values
      (new.client_id, 'p05b.sent', 'done', 'נסגר לבד: הלקוח מילא את טופס פרטי הכניסה'),
      (new.client_id, 'p05.allnets', 'done', 'נסגר לבד: הלקוח מילא בטופס את הרשתות שלו')
    on conflict (client_id, item_key) do update set state = 'done', note = excluded.note
      where public.protocol_checks.state <> 'done';
  end if;
  return new;
end $$;
-- Trigger functions are not an API: only the trigger calls them.
revoke execute on function public.client_access_links_filled() from public, anon, authenticated;
create or replace trigger client_access_links_zz_filled after update on public.client_access_links
for each row execute function public.client_access_links_filled();

-- ── 4. Who writes which protocol item (v8) ───
-- The new items are Irit's, and the office writes every key, so no row is added. Lior
-- left the review of the first graphics, so he is out of the two rules of process 7
-- (he is of the office and writes every key anyway). From this version on the block
-- writes each row over its key instead of emptying the table first.
-- protocol-writers:begin (generated by scripts/protocol-writers.mjs from app/protocol.js; do not edit by hand)
insert into private.protocol_writers (key, proc, round, persons) values
  ('@office', null, false, array['irit', 'lior', 'ofir']::text[]),
  ('@editors', null, false, array['anna', 'nadia', 'nirel', 'yariv']::text[]),
  ('p05.newlogo', 'p05', false, array['ilai']::text[]),
  ('p05.@wait', 'p05', false, array['ilai', 'irit', 'lior', 'ofir']::text[]),
  ('p05.@part', 'p05', false, array['ilai', 'irit', 'lior', 'ofir']::text[]),
  ('p06.verified', 'p06', false, array['ilai']::text[]),
  ('p06.newpages', 'p06', false, array['ilai']::text[]),
  ('p06.name', 'p06', false, array['ilai']::text[]),
  ('p06.bio', 'p06', false, array['ilai']::text[]),
  ('p06.details', 'p06', false, array['ilai']::text[]),
  ('p06.phone', 'p06', false, array['ilai']::text[]),
  ('p06.address', 'p06', false, array['ilai']::text[]),
  ('p06.look', 'p06', false, array['ilai']::text[]),
  ('p06.metricool', 'p06', false, array['ilai']::text[]),
  ('p06.@part', 'p06', false, array['ilai', 'lior']::text[]),
  ('p07.made', 'p07', false, array['ilai']::text[]),
  ('p07.@wait', 'p07', false, array['ilai', 'irit']::text[]),
  ('p07.@part', 'p07', false, array['ilai', 'irit']::text[]),
  ('p07b.posted', 'p07b', false, array['ilai']::text[]),
  ('p07b.@part', 'p07b', false, array['ilai']::text[]),
  ('p09.file', 'p09', false, array['ilai']::text[]),
  ('p09.c.name', 'p09', false, array['ilai']::text[]),
  ('p09.c.months', 'p09', false, array['ilai']::text[]),
  ('p09.c.num', 'p09', false, array['ilai']::text[]),
  ('p09.c.link', 'p09', false, array['ilai']::text[]),
  ('p09.c.day', 'p09', false, array['ilai']::text[]),
  ('p09.c.date', 'p09', false, array['ilai']::text[]),
  ('p09.c.time', 'p09', false, array['ilai']::text[]),
  ('p09.@part', 'p09', false, array['ilai']::text[]),
  ('p17b.arrived', 'p17b', true, array['eli']::text[]),
  ('p17b.drive', 'p17b', true, array['eli']::text[]),
  ('p17b.gear', 'p17b', true, array['eli']::text[]),
  ('p17b.zones', 'p17b', true, array['eli']::text[]),
  ('p17b.broll', 'p17b', true, array['eli']::text[]),
  ('p17b.variety', 'p17b', true, array['eli']::text[]),
  ('p17b.@part', 'p17b', true, array['eli']::text[]),
  ('p18b.order', 'p18b', true, array['eli']::text[]),
  ('p18b.quality', 'p18b', true, array['eli']::text[]),
  ('p18b.numbered', 'p18b', true, array['eli']::text[]),
  ('p18b.@part', 'p18b', true, array['eli']::text[]),
  ('p19b.folders', 'p19b', true, array['eli']::text[]),
  ('p19b.complete', 'p19b', true, array['eli']::text[]),
  ('p19b.opens', 'p19b', true, array['eli']::text[]),
  ('p19b.cards', 'p19b', true, array['eli']::text[]),
  ('p19b.handed', 'p19b', true, array['eli']::text[]),
  ('p19b.notes', 'p19b', true, array['eli']::text[]),
  ('p19b.@part', 'p19b', true, array['eli']::text[]),
  ('p22.received', 'p22', true, array['@editor']::text[]),
  ('p22.check.footage', 'p22', true, array['@editor']::text[]),
  ('p22.check.scripts', 'p22', true, array['@editor']::text[]),
  ('p22.check.logo', 'p22', true, array['@editor']::text[]),
  ('p22.check.phone', 'p22', true, array['@editor']::text[]),
  ('p22.edited', 'p22', true, array['@editor']::text[]),
  ('p22.self.spelling', 'p22', true, array['@editor']::text[]),
  ('p22.self.broll', 'p22', true, array['@editor']::text[]),
  ('p22.self.closing', 'p22', true, array['@editor']::text[]),
  ('p22.self.complete', 'p22', true, array['@editor']::text[]),
  ('p22.@wait', 'p22', true, array['@editor']::text[]),
  ('p22.@pause', 'p22', true, array['@editor', '@editor-free']::text[]),
  ('p22.@part', 'p22', true, array['@editor']::text[]),
  ('p23.made', 'p23', false, array['ilai']::text[]),
  ('p23.@wait', 'p23', false, array['ilai', 'irit', 'ofir']::text[]),
  ('p23.@part', 'p23', false, array['ilai', 'irit', 'ofir']::text[]),
  ('p23b.posted', 'p23b', false, array['ilai']::text[]),
  ('p23b.@part', 'p23b', false, array['ilai']::text[]),
  ('p24.drive', 'p24', true, array['@editor']::text[]),
  ('p24.d' || 'ropbox', 'p24', true, array['@editor']::text[]),
  ('p24.notify', 'p24', true, array['@editor']::text[]),
  ('p24.@wait', 'p24', true, array['@editor', 'ofir']::text[]),
  ('p24.@part', 'p24', true, array['@editor', 'ofir']::text[]),
  ('p27.fixes', 'p27', true, array['@editor']::text[]),
  ('p27.final', 'p27', true, array['@editor']::text[]),
  ('p27.toilai', 'p27', true, array['ilai']::text[]),
  ('p27.@wait', 'p27', true, array['@editor', 'ilai', 'irit']::text[]),
  ('p27.@pause', 'p27', true, array['@editor', '@editor-free']::text[]),
  ('p27.@part', 'p27', true, array['@editor', 'ilai', 'irit']::text[]),
  ('p28.scheduled', 'p28', true, array['ilai']::text[]),
  ('p28.@part', 'p28', true, array['ilai']::text[]),
  ('p29.filled', 'p29', true, array['ilai']::text[]),
  ('p29.@claim', 'p29', true, array['ilai', 'irit']::text[]),
  ('p29.@part', 'p29', true, array['ilai', 'irit']::text[]),
  ('p17b.brollq', 'p17b', true, array['eli']::text[]),
  ('p22.missing', 'p22', true, array['@editor']::text[]),
  ('p27.fixed', 'p27', true, array['@editor']::text[]),
  ('p25.@qafixed', 'p25', true, array['@editor']::text[]),
  ('p23.@qafixed', 'p23', false, array['ilai']::text[])
on conflict (key) do update set proc = excluded.proc, round = excluded.round, persons = excluded.persons;
update private.protocol_writers set persons = '{}'::text[] where key <> all (array['@office', '@editors', 'p05.newlogo', 'p05.@wait', 'p05.@part', 'p06.verified', 'p06.newpages', 'p06.name', 'p06.bio', 'p06.details', 'p06.phone', 'p06.address', 'p06.look', 'p06.metricool', 'p06.@part', 'p07.made', 'p07.@wait', 'p07.@part', 'p07b.posted', 'p07b.@part', 'p09.file', 'p09.c.name', 'p09.c.months', 'p09.c.num', 'p09.c.link', 'p09.c.day', 'p09.c.date', 'p09.c.time', 'p09.@part', 'p17b.arrived', 'p17b.drive', 'p17b.gear', 'p17b.zones', 'p17b.broll', 'p17b.variety', 'p17b.@part', 'p18b.order', 'p18b.quality', 'p18b.numbered', 'p18b.@part', 'p19b.folders', 'p19b.complete', 'p19b.opens', 'p19b.cards', 'p19b.handed', 'p19b.notes', 'p19b.@part', 'p22.received', 'p22.check.footage', 'p22.check.scripts', 'p22.check.logo', 'p22.check.phone', 'p22.edited', 'p22.self.spelling', 'p22.self.broll', 'p22.self.closing', 'p22.self.complete', 'p22.@wait', 'p22.@pause', 'p22.@part', 'p23.made', 'p23.@wait', 'p23.@part', 'p23b.posted', 'p23b.@part', 'p24.drive', 'p24.d' || 'ropbox', 'p24.notify', 'p24.@wait', 'p24.@part', 'p27.fixes', 'p27.final', 'p27.toilai', 'p27.@wait', 'p27.@pause', 'p27.@part', 'p28.scheduled', 'p28.@part', 'p29.filled', 'p29.@claim', 'p29.@part', 'p17b.brollq', 'p22.missing', 'p27.fixed', 'p25.@qafixed', 'p23.@qafixed']::text[]);
-- protocol-writers:end
